### PR TITLE
Update to add cookies and expiration options

### PR DESCRIPTION
**Pull request by jcgertig**

### CODE REVIEW

**Comment by undercase** [comment]
Hey Jonathan - could you send me a brief description of the changes you've made /  features you've added in this pull request so I can review it?

**Comment by jcgertig** [comment]
Yes this adds support for proof to set a cookie with the token if wanted and allows for experation date on the token to be set properly and turned off if wanted. It also allows for the header name to be customised.

**Comment by jcgertig** [comment]
Still need to update a few tests was also testing my branch on rails 5

**Comment by undercase** [comment]
Awesome, thanks for these changes. Let me know once you've updated the tests and I'll take a look.

**Comment by jcgertig** [comment]
@undercase the tests pass locally for me 

```
# Running:

...........

Finished in 0.100135s, 109.8519 runs/s, 229.6904 assertions/s.

11 runs, 23 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by undercase** [comment]
Looks good, thanks.

**Pull request merged**
